window.onload = initGame; //Calls the initGame function when the browser is opened

function initGame() //the purpose of this function is to call the functions and variables that are needed on page load for the bingo game to work
{
	generateCard(); //calls the generate card function
}

function generateCard() //the purpose of this function is to generate random numbers and populate each square in the bingo card
{
	for (var i = 0; i < 24; i++) //start i at 0, keep looping whilst i is less than 24, increment i by one every time the operator is completed.
	{
		let randomNumber = Math.floor(Math.random() * 75) +1; //generates a random number between 0-1 using the math object, then times it by the highest number I want (75), add 1 to prevent the number 0 coming up.
		document.getElementById("square" + i).innerHTML = randomNumber; //populate the current square with the number generated by the math object.
	}
}
